version: '3'
services:
  # Spring Boot application
  spring-app:
    image: your-spring-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3308/middleware
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bhimeshpatil@1
    depends_on:
      - mysql-db

  # MySQL database
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Bhimeshpatil@1
      MYSQL_DATABASE: middleware
      MYSQL_USER: root
      MYSQL_PASSWORD: Bhimeshpatil@1